# Generated by Django 2.0.2 on 2018-02-20 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messageApp', '0003_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
